highlighter: rouge
permalink: /:categories/:year/:month/:day/:title
title: 'RnF Web Services Production Timeline for RyersonSoccer.com'
url: "http://pro.ryersonsoccer.com"
baseurl: ""

# Sets the default folder in Prose.io
# Sets the default metadata in Prose.io
prose:
  rooturl: "_posts"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
